### ISSUE TITLE
URI primitive type not supported

### ISSUE THREAD

**Issue by hatim-ez** [LiveRamp/reslang#103]
Swagger supports different format modifiers for a string type, `uri` being one of them:
```
inputDataURL:
          type: string
          description: "URL of the data to be distributed. Currently, we only support files
            in GCS.  "
          format: uri
          example: https://storage.google.com/buckets/my-bucket/dog-lovers-campaign.csv
```

However, reslang only supports the `url` string format (https://github.com/LiveRamp/reslang/blob/master/src/genbase.ts#L920-L927). 

It would be nice to have reslang either support customizable string formats, or just add support for the `uri` one.
