### ISSUE TITLE
Incorporate securitySchemes

### ISSUE THREAD

**Issue by conrs** [LiveRamp/reslang#111]
e.g.
```
security:
  - LROrgId: []
  - BearerToken: []

components:
  parameters: {}
  securitySchemes:
    LROrgId:
      type: apiKey
      in: header
      name: LR-Org-Id
    BearerToken:
      type: http
      scheme: bearer
``` 

Useful to call out and the above are the standard auth and org ID specifications.
