### ISSUE TITLE
Reslang generates invalid schema for custom events

### ISSUE THREAD

**Issue by JacobCrofts** [LiveRamp/reslang#183]
Medium priority, not high, because even though the spec is invalid, no functionality is lost. We just get an annoying error message alongside our otherwise working docs.

**Describe The Bug**

When I say custom events, this is an example of what I mean:

```
event SegmentIngestionCompleted {
    /payload
	    segmentIngestionRequest: value-of SegmentIngestionRequest
}
produces SegmentIngestionCompleted
```

Reslang produces an invalid AsyncAPI schema for custom events. You can see the errors at the top of [this page](https://internal-apis.corp.liveramp.com/segment-management-events).

The problem is that the UI tool we are using does not accept the following with an empty `enum`:

```yaml
    SegmentIngestionRequestHeader:
      type: object
      properties:
        verb:
          description: ''
          type: string
          enum: [] # delete this line and it will be valid
```

After fixing this single issue manually, the [AsyncAPI editor](https://playground.asyncapi.io/) seems to be happy.

**To Reproduce**

see top of [this page](https://internal-apis.corp.liveramp.com/segment-management-events)

**Expected Behavior**

Doc portal page linked above displays no errors. This most likely means updating reslang so that it excludes empty request header enums. We could also consider removing that field entirely, as it's not obvious to me how it would be useful. Normally the enum is populated with HTTP verbs.

**Reslang Version**

Master/Latest
