### ISSUE TITLE
Put `format` attribute under the `items` attribute for array properties

### ISSUE THREAD

**Issue by lmossman** [LiveRamp/reslang#42]
The Field API defines an [fieldIDs array field](https://github.com/LiveRamp/api-specs/blob/master-proposals/dm-field-api/field.reslang#L60) for the bulk disable action. This generated swagger that looks like [this](https://github.com/LiveRamp/api-specs/blob/master-proposals/dm-field-api/field-api.yaml#L293-L299):
```
        fieldIDs:
          description: IDs of Fields to disable.
          format: int64
          items:
            type: integer
            example: 'Link to Audience::Field resource(s) via id(s)'
          type: array
```
This is slightly incorrect, as the `format: int64` line should be underneath the `items` attribute, as the `int64` format applies to the `integer` items. The above swagger generates a Java class with `fieldIDs` as a list of Integers, rather than Longs as is desired.

This should be fixed by changing reslang to generate swagger that has the `format` underneath the `items` attribute for array properties. Here is what the correct swagger should look like:
```
        fieldIDs:
          description: IDs of Fields to disable.
          items:
            type: integer
			format: int64
            example: 'Link to Audience::Field resource(s) via id(s)'
          type: array
```
